services:
  api:
    build: 
      context: api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment: 
      DB_URL: jdbc:postgresql://192.168.60.206:5432/postgres?currentSchema=thai_tour&sslmode=disable    
      DB_USERNAME: postgres   
      DB_PASSWORD: new_password 
  web:
    build:  
      context: web
      dockerfile: Dockerfile
    ports:
      - 80:3000  
    depends_on:
      - api