server:
  port: '8080'
spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: 'smtp.gmail.com'
    username: 'daniel.jantulik@gmail.com'
    password: 'jboa gvfo fqid mnxb'
    port: '587'
  security:
    user:
      name: admin
      password: admin
      roles: manager
  datasource:
    jdbc-url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  autoconfigure:
    exclude:
      - >-
        org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
