server:
  port: '8080'
spring:
  security:
    user:
      name: admin
      password: admin
      roles: manager
  datasource:
    jdbc-url: 'jdbc:postgresql://192.168.60.206:5432/postgres?currentSchema=thai_tour&sslmode=disable'
    username: postgres
    password: new_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: false
    baseline-on-migrate: true
  autoconfigure:
    exclude:
      - >-
        org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
