insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Summit Green Valley Country Club',
       'https://www.thaitour.cz/wp-content/uploads/Green-220x165.gif',
        'Golfové hřiště Summit Green Valley Country Club v Chiang Mai bylo postaveno v roce 1990. Toto úchvatné hřiště navrhl pan Dennis Griffiths, který také navrhl golfové hřiště Thai Country Club v Bangkoku. Summit Green Valley Country Club je vždy obsazeno a jde o velmi...',
        3000,
        '186 M.1 Chotana Rd.,Maesa,Maerim,Chiangmai 50180 Thajsko',
        18.9122,
        98.9397,
        '18',
        '7202',
        '72',
        'Denně',
        'Ano',
        '1990',
        'Denis Griffiths',
        false,
        true,
        null, 'ADMIN' , null, null);


insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Mae Jo Golf Club & Resort',
        'https://www.thaitour.cz/wp-content/uploads/14-32-220x165.jpg',
        'Mae Jo Golf Club & Resort je snadno dostupné golfové hřiště, které se nachází hned vedle Mae Jo univerzity (nejstarší zemědělská škola v Chiang Mai) a je pouhých 20 minut jízdy od města Chiang Mai. Golfové hřiště navrhl známý architekt pan Seni Thirawat. Mae Jo...',
        2250,
        '112 Moo 7 Ban Sriboonruang, Pahpai Sansia, Chiang Mai, 50210 Thajsko',
        18.8522,
        99.0453,
        '18',
        '6657',
        '72',
        'Denně',
        'Ano',
        '2004',
        'Seni Thirawat',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Chiang Mai Inthanon Golf Resort',
        'https://www.thaitour.cz/wp-content/uploads/14-32-220x165.jpg',
        'Chiang Mai Inthanon Golf Resort je top golfové hřiště vysoké kvality na jednom z nejvyšších thajských vrcholů v krásné oblasti a přírodě Chiang Mai. Golfové hřiště je malebné golfové hřiště s panoramatickými výhledy na nejvyšší horu Thajska Doi Inthanon, která...',
        3000,
        '99 Moo.13 T.Khuangpao, A.Jomthong, Chiang Mai 50160 Thajsko',
        18.4269,
        98.6781,
        '18',
        '7202',
        '72',
        'Denně',
        'Ano',
        '1990',
        'Denis Griffiths',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Chiang Mai Highlands Golf & Spa',
        'https://www.thaitour.cz/wp-content/uploads/14-32-220x165.jpg',
        'Chiang Mai Highlands Golf & Spa bylo otevřeno v roce 2005, čímž významně přispělo ke kvalitě golfových hřišť v oblasti Chiang Mai. Nachází se 1000 m n.m. Golfové hřiště s 18 jamkami navrhl Lee Schmidt, světový designér, který se pokusil zachytit krásu Chiang...',
        3500,
        '167 Moo 2 Onuar, Mae On, Chiang Mai 50130 Thajsko',
        18.7422,
        99.1225,
        '18',
        '7268',
        '72',
        'Denně',
        'Ano',
        '2009',
        'Suphachai Silamon',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Alpine Chiang Mai Golf Resort',
        'https://www.thaitour.cz/wp-content/uploads/14-32-220x165.jpg',
        'Ronald M. Garl je jeden z nejlepších světových návrhářů golfových hřišť a vyhrál ocenění „Nejlepší designér golfových hřišť“ v roce 1996. Golfová hřiště navrhoval i na Floridě. Golfové hřiště Alpine Chiang Mai Golf Resort se rozléhá na 178 akrů pozemku, umístěného...',
        4050,
        '336 moo 4 Tambon huay-yab Ampher banthi Lamphun 51180, Thajsko',
        18.58054,
        99.00745,
        '18',
        '7541',
        '72',
        'Denně',
        'Ano',
        '2008',
        'Ronald M. Garl',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Red Mountain Golf Club',
        'https://www.thaitour.cz/wp-content/uploads/14-32-220x165.jpg',
        'The Red Mountain Golf Club se rychle stalo jedním z asijských nejlepších hřišť již od svého otevření v roce 2007. Hřiště se točí přes drsnou krajinu starého cínového dolu. Hřiště nabízí vzrušující hru a ohromující rozmanitost přírody včetně husté džungle. The Red...',
        4980,
        '119 Moo 4 Vichitsongkram Rd.,Kathu District, Phuket 83120, Thajsko',
        7.9167,
        98.35,
        '18',
        '6905',
        '72',
        'Denně',
        'Ano',
        '2007',
        'Johnathan Morrow',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Phuket Country Club',
        'https://www.thaitour.cz/wp-content/uploads/14-32-220x165.jpg',
        'Phuket Country Club byl založen v roce 1989 a jedná se o jedno z nejlepších golfových hřišť na Phuketu a zároveň o úplně první golfové hřiště tohoto ostrova na mezinárodní úrovni, které hostilo již několik národních turnajů. Toto 27 jamkové golfové hřiště je doslova...',
        4050,
        '80/1 Moo 7, Vichit Songkram Road, Kathu District, Phuket 83120, Thajsko',
        7.9167,
        98.35,
        '27',
        '6484/7150',
        '72/36',
        'Denně',
        'Ano',
        '1989',
        'Denis Griffiths',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Mission Hills Phuket Golf Resort & Spa',
        'https://www.thaitour.cz/wp-content/uploads/14-32-220x165.jpg',
        'Golfové hřiště Mission Hills Phuket Golf Resort & Spa je zasazeno mezi kaučukové plantáže a malebném pobřežní mangrovových lesů na severu ostrova Phuket, pouhých 10 min. od mezinárodního letiště. Toto 18 jamkové hřiště je populární volbou pro příležitostné...',
        3600,
        '195 Moo 4 Pa khlok, Amphur Thalang, Phuket 83110 Thajsko',
        7.9833,
        98.3667,
        '18',
        '6806',
        '72',
        'Denně',
        'Ano',
        '2004',
        'Jack Nicklaus',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Loch Palm Golf Club',
        'https://www.thaitour.cz/wp-content/uploads/14-32-220x165.jpg',
        'Golfové hřiště Loch Palm Golf Club bylo postaveno v roce 1993 kolem jezera Crystal Lake, které tvoří největší vodní útvar ze všech golfových hřišť na Phuketu. V okolí hřiště je panoramatické pozadí džungle a krásné hory. Loch Palm Golf Club má hladké svahy a...',
        3900,
        '38 Moo 5 Vichitsongkram Rd., Kathu District, Phuket 83120, Thajsko',
        7.9167,
        98.35,
        '18',
        '6555',
        '72',
        'Denně',
        'Ano',
        '1993',
        'Dr. Sukitti Klangvisai',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Blue Canyon Country Club – Lakes Course',
        'https://www.thaitour.cz/wp-content/uploads/14-32-220x165.jpg',
        'Blue Canyon Country Club – Lakes Course bylo založeno v roce 1999 architektem Yoshikazu Kato, který vytvořil mistrovské hřiště vysoce všemi oceňované. Architekt využil přírodní krajinu a autentické krásy okolí a vytvořil toto mistrovské náročné golfové hřiště...',
        4850,
        '165, Moo 1, Thepkasattri Rd | Thalang, Phuket 83110, Thajsko',
        7.9833,
        98.3667,
        '18',
        '7179',
        '72',
        'Denně',
        'Ano',
        '1999',
        'Yoshikazu Kato',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Blue Canyon Country Club – Canyon Course',
        'https://www.thaitour.cz/wp-content/uploads/14-32-220x165.jpg',
        'Blue Canyon Country Club – Canyon Course je hodnoceno jako jedno z nejprestižnějších golfových klubů v Asii, které bylo již min. 4x zvoleno jako nejlepší hřiště v Asii. Hřiště je proslulé díky dvojímu hostování turnaje Johnnie Walker Classics Tournament (1994 a...',
        5650,
        '165, Moo 1, Thepkasattri Rd | Thalang, Phuket 83110, Thajsko',
        7.9833,
        98.3667,
        '18',
        '7179',
        '72',
        'Denně',
        'Ano',
        '1991',
        'Yoshikazu Kato',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Springfield Royal Country Club',
        'https://www.thaitour.cz/wp-content/uploads/14-32-220x165.jpg',
        'Springfield Royal Country Club patří k nejlepším golfovým hřištím v oblasti Hua Hin, která je vzdálená cca 30 minut od centra města a nedaleko Bangkoku. Hřiště svým designem splňuje požadavky mistrovského hřiště a hru si zde naplno užijí hráči všech úrovní....',
        2950,
        '208, Moo 2, Sampraya, Cha – am, Phetchburi 76120, Thajsko',
        12.8,
        99.9667,
        '27',
        '7043',
        '72',
        'Denně',
        'Ano',
        '1993',
        'Jack Nicklaus',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Sea Pine Golf Club',
        'https://www.thaitour.cz/wp-content/uploads/14-32-220x165.jpg',
        'Sea Pines Golf Course (také známý jako Army Golf Club II) se nachází u Thajského zálivu v Suan Son Pradiphat (Sea Pine Tree Garden). Golfové hřiště v oblasti Hua Hin leží cca 20 min. od Hua Hin a pláže Suan Son Pradiphat Beach. Toto hřiště bylo kreativně zasazeno na...',
        3400,
        'Phetkasem Rd. Nong Kae, Hua Hin, Prachuap Khiri Khan 77110, Thajsko',
        12.8,
        99.9667,
        '18',
        '7305',
        '72',
        'Denně',
        'Ano',
        '2010',
        'Major General W. Phetbuasak',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Royal Hua Hin Golf Club',
        'https://www.thaitour.cz/wp-content/uploads/14-32-220x165.jpg',
        'Royal Hua Hin Golf Course je nejstarší 18 ti jamkové mezinárodní golfové hřiště v Thajsku. Ve 2. desetiletí 20. století skotský železniční inženýr jménem O. A. Robins navrhl právě toto 1. golfové hřiště Thajska, které bylo otevřeno již v roce 1924 a leží méně jak...',
        2880,
        'Hua Hin Prachuab Khiri Khan, Thajsko, 77110',
        12.5667,
        99.9667,
        '18',
        '6678',
        '72',
        'Denně',
        'Ano',
        '1924',
        'A. O. Robins',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Palm Hills Resort & Golf Club',
        'https://www.thaitour.cz/wp-content/uploads/14-32-220x165.jpg',
        'Palm Hills Golf Club & Residence nabízí golfové hřiště světové třídy a butikový životní styl a zařízení 80 m n. m. Slibuje nezapomenutelný golfový zážitek v přírodním prostředí, na který budete rádi vzpomínat celý život. To vše v prestižní čtvrti Hua Hin – Cha...',
        2450,
        '1444 Petchkasem Rd., Cha-am, Petchburi 76120, Thajsko',
        12.8,
        99.9667,
        '18',
        '6892',
        '72',
        'Denně',
        'Ano',
        '1992',
        'Max Wexler',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Majestic Creek Country Club',
        'https://www.thaitour.cz/wp-content/uploads/14-32-220x165.jpg',
        'V roce 1995 zkušený thajský architekt, Dr Sukitti Klangvisai, vytvořil skutečně skvostné golfové hřiště vetkané do potoků naproti ohromujícímu pozadí pohoří na hranicích s Barmou, nazývané Majestic Creek. Stavitelé hřiště byli opatrní, aby uchovali všechny přírodní...',
        2550,
        '164 moo 4, Tubtai Hua Hin, Prachuabkirikhan, 77110 Thajsko',
        12.5531214,
        99.9432952,
        '27',
        '7035',
        '72/36',
        'Denně',
        'Ano',
        '1995',
        'Dr. Sukitti Klangvisai',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Imperial Lakeview Golf Club',
        'https://www.thaitour.cz/wp-content/uploads/14-32-220x165.jpg',
        'Imperial Lake View Resort & Golf Club bylo první 36 jamkové golfové hřiště v oblasti Hua Hin – Cha-am, cca 35 min. od centra města. Pokud uvažujete o ideálním útěku do klidného a krásného prostředí nedaleko Bangkoku, pak je Imperial Lake View Resort &...',
        1950,
        '79 Moo 4, Tambol Sampraya, Cha Am, Petchaburi. Thajsko, 76120',
        12.8,
        99.9667,
        '18',
        '6915',
        '36',
        'Denně',
        'Ano',
        '1993',
        'Roger Packard',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Black Mountain Golf Club',
        'https://www.thaitour.cz/wp-content/uploads/14-32-220x165.jpg',
        'Black Mountain je world-class Championship golfové hřiště a je jedním z nejvíce vzrušujících, vyzývajících a nezapomenutelných hřišť v Asii. Zde zažijete to nejlepší z golfu, krásné prostředí, úžasné výhledy téměř z každé jamky, příjemný design a i mnoho výzev pro...',
        3550,
        '186 M.1 Chotana Rd.,Maesa,Maerim,Chiangmai 50180 Thajsko',
        12.5667,
        99.9667,
        '18',
        '7343',
        '72',
        'Denně',
        'Ano',
        '2007',
        'Phil Ryan',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Banyan Golf Club',
        'https://www.thaitour.cz/wp-content/uploads/14-32-220x165.jpg',
        'Mistrovské golfové hřiště Banyan Golf Club s klubovnou již tři roky po sobě získalo hodnocení „nejlepší“ hřiště od Asian Golf Monthly. Hřiště Banyan Golf Club také vystupovalo v Top 1000 od World by Rolex. Hřiště bylo otevřeno v roce 2008 a návštěvníkům zajišťuje...',
        3150,
        '186 M.1 Chotana Rd.,Maesa,Maerim,Chiangmai 50180 Thajsko',
        12.57065,
        99.95876,
        '18',
        '7361',
        '72',
        'Denně',
        'Ano',
        '2008',
        'Golf East (Pirapon Namatra)',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Waterford Valley Chiang Rai',
        'https://www.thaitour.cz/wp-content/uploads/14-32-220x165.jpg',
        'Waterford Valley Chiang Rai Golf Course je překrásné 18 jamkové hřiště obklopené horami. Golfové hřiště navrhl Mark Rathert a vytvořil mistrovské hřiště. Toto kopcovité hřiště poskytuje vzácný golfový zážitek i pro golfové veterány. K dispozici jsou i různé...',
        1750,
        'No. 333 Moo 5 T.Pasasng A.Wiangchairung, Chaingrai 57210 Thajsko',
        19.8833,
        99.9167,
        '18',
        '6961',
        '72',
        'Denně',
        'Ano',
        '1997',
        'Rathert International Golf Design',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Santiburi Chiang Rai Country Club',
        'https://www.thaitour.cz/wp-content/uploads/2011343632-220x165.jpg',
        'Santiburi Country Club je první a největší 18 jamkové hřiště, které navrhl jeden z nejlepších designérů světa, designér Robert Trent Jones Jr. Jedná se o jedno z nejlepších golfových hřišť světových designérů. Hřiště leží na severu Thajska a jde o krásný golfový...',
        1890,
        '12 Moo 3 Tumbol Wiang-Chai, Wiang-cha, District Chiang Rai 57210, Thajsko',
        19.90858,
        99.8325,
        '18',
        '6853',
        '72',
        'Denně',
        'Ano',
        '1993',
        'Robert Trent Jones Jr.',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Happy City Golf Resort',
        'https://www.thaitour.cz/wp-content/uploads/10897801_586229034811542_6808601147086537999_n-220x165.jpg',
        'Happy City Golf Resort je 29 jamkové mistrovské golfové hřiště v podhůří severního Thajska, které se nachází na malebném pohoří a údolí řek a bylo poprvé otevřeno v roce 2012. Jedná se o nejnovější golfové hřiště v Chiang Rai, které se stále snaží zdokonalovat a...',
        1150,
        '22 Moo 10 Muangchoom Sub-district, Wiang Chai District, Chiang Rai, 57210 Thajsko',
        19.4881446,
        99.4767143,
        '29',
        '7036',
        '72/36',
        'Denně',
        'Ano',
        '2012',
        'Daengchuang & Srisuphachaiya',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('St Andrews 2000 Golf Club',
        'https://www.thaitour.cz/wp-content/uploads/150-338-220x165.jpg',
        'St. Andrews 2000 Golf Club v Rayong, cca 40 min. jízdy od města Pattaya a 2 hodiny od Bangkoku, v roce 2000 navrhl Desmond Muirhead. Toto krásné hřiště se nachází 120 km jihovýchodně od Bangkoku a chvilku od přímořského letoviska Pattaya. Pokud cestujete do Thajska...',
        2250,
        '9/36 Moo 7 Samnakthon Banchang Rayong 21130, Thajsko',
        19.4881446,
        99.4767143,
        '18',
        '7777',
        '72',
        'Denně',
        'Ano',
        '2000',
        'Desmond Muirhead',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Siam Country Club (Old, Plantation, Waterside)',
        'https://www.thaitour.cz/wp-content/uploads/siam-country-club-plantation-course-220x165.jpg',
        'Siam Country Club Pattaya nabízí tři hřiště: Old Course, Plantation Course a Waterside Course, všechna jsou vzdálena cca 25 min. jízdy od města Pattaya a navržené Izumi, Schmidt a Curley, IMG Golf Course Design. Pro negolfisty je k dispozici restaurace, sauna,...',
        4700,
        '50 Moo 9 T. Banglamung,, Pong, Bang Lamung District, Chon Buri 20150, Thajsko',
        19.4881446,
        99.4767143,
        '18',
        '7016',
        '72',
        'Denně',
        'Ano',
        '1971',
        'Izumi, Schmidt a Curley',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Laem Chabang International Country Club',
        'https://www.thaitour.cz/wp-content/uploads/golf-laemchabang-220x165.jpg',
        'Při návštěvě Thajska byste si neměli nechat ujít golfové hřiště světového standardu Laem Chabang International Country Club. Toto skvělé hřiště navrhl a doporučuje slavný golfista Jack Nicklaus. Toto mistrovské hřiště je jedním z nejlepších v oblasti Pattaya a...',
        2450,
        '106/8 Moo 4, Beung, Sriracha, Chonburi 20230, Thajsko',
        19.4881446,
        99.4767143,
        '18',
        '7202',
        '72',
        'Denně',
        'Ano',
        '1995',
        'Jack Nicklaus',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Phoenix Golf & Country Club',
        'https://www.thaitour.cz/wp-content/uploads/Phoenix-Golf-Country-Club.jpg-220x165.jpg',
        'Phoenix Golf & Country Club se nachází na zvlněném zalesněném terénu v nádherné zeleni plné eukalyptů, bambusů, mangovníků a květin. Má prostornou klubovnu se střechou v barvách sluníčka. Toto hřiště je příjemným mezníkem pro místní i mezinárodní golfisty....',
        2850,
        '111 Moo 9, Sukhaphiban 2 Road, Huayyai, Banglamung Chonburi 20150, Thajsko',
        19.4881446,
        99.4767143,
        '27',
        '6812/3261',
        '72/36',
        'Denně',
        'Ano',
        '1993',
        'Dennis Griffiths',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Rayong Green Valley Country Club',
        'https://www.thaitour.cz/wp-content/uploads/rayong-green-valley-country-club-510fbc3325f77-220x165.jpg',
        'Rayong Green Valley Country Club přitahuje golfisty, kteří chtějí překonat sami sebe. Příroda a krajina na hřišti má vrchy, skály, balvany, kaktusy, původní faunu a svažující se fairways. Tento přírodní výtvor se i nadále uchoval, když se tato krásná krajina...',
        1880,
        '9/36 Moo7, Samnakthon Banchang, Rayong 21130, Thajsko',
        19.4881446,
        99.4767143,
        '18',
        '7096',
        '72',
        'Denně',
        'Ano',
        '1992',
        'Peter Thomson',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Khao Kheow Golf Club',
        'https://www.thaitour.cz/wp-content/uploads/Khao-Kheow-B9_shrink-220x165.jpg',
        'Khao Kheow Country Club je 27 jamkové hřiště přírodní elegance s jedinečným designem leží v samém srdci golfového koridoru Pattaya u hlavní silnice při cestě do Bangkoku. Hřiště nabízí hru pro golfové nadšence všech úrovní, jak pro začátečníky, tak pro profesionály....',
        2350,
        '220/15 Moo12, Bangphra Siracha, Chonburi 20210, Thajsko',
        19.4881446,
        99.4767143,
        '27',
        '7077',
        '72-36',
        'Denně',
        'Ano',
        '1992',
        'Pete Dye',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Royal Chiang Mai Golf Club & Resort',
        'https://www.thaitour.cz/wp-content/uploads/Royal-Chaing-Mai-Green-220x165.jpg',
        'Royal Chiang Mai Golf Club & Resort se nachází pouhých 30 min. od města Chiang Mai mezi zalesněnými kopci a chladivými klidnými horskými potoky. Je to skvělé místo pro celou rodinu nejen pro golf, ale i pro rekreaci a odpočinek. Toto úchvatné 18 jamkové hřiště...',
        1900,
        '169 Moo 5, San Sai-Phrao Road, Maefak Sub-District, San Sai District, 50290 Thajsko',
        19.4881446,
        99.4767143,
        '18',
        '6969',
        '72',
        'Denně',
        'Ano',
        '1996',
        'Peter Thomson',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Burapha Golf Club',
        'https://www.thaitour.cz/wp-content/uploads/Burapha-Golf-Club-003-220x165.jpg',
        'Burapha Golf Club se nachází v Sriracha, provincii Chonburi ve východní části Thajska a nachází se jen 109 km od Bangkoku a 30 km od města Pattaya, jedné z největších turistických destinací Thajska. Hřiště se nachází v kopcovité krajině v blízkosti nové Chonburi...',
        2850,
        '281 Moo 4, Si Racha, Si Racha, Chonburi 20110 Thaisko',
        19.4881446,
        99.4767143,
        '36',
        '6948',
        '72',
        'Denně',
        'Ano',
        '1993',
        'David Graham & Gary Panks',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Santiburi Samui Country Club',
        'https://www.thaitour.cz/wp-content/uploads/santiburi1-220x165.jpg',
        'Santiburi Samui Country Club je 18 jamkové golfové hřiště, které je známé jako jedno z nejkrásnějších golfových hřišť v Asii a je nezbytnou zastávkou pro PGA Asian Tour po mnoho let. Hřiště bylo zařazeno do TOP 5 golfových hřišť v Thajsku. Santiburi Samui Country...',
        4900,
        '12/12 Moo 1, Maenam Beach, Koh Samui, Surat Thani 84330, Thajsko',
        19.4881446,
        99.4767143,
        '18',
        '6824',
        '72',
        'Denně',
        'Ano',
        '2003',
        'E. Thiele & P. Namatra',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('The Royal Gems Golf City',
        'https://www.thaitour.cz/wp-content/uploads/gl2b-220x165.jpg',
        'Golfisté si často přejí hrát na těch nejlepších golfových hřištích a jsou ochotni cestovat i daleko do světa za největšími a nejlepšími golfovými hřišti. Právě The Royal Gems Golf City je nejnovější a nejvíce vzrušující golfové hřiště v jihovýchodní Asii, jde o...',
        3050,
        '186 M.1 Chotana Rd.,Maesa,Maerim,Chiangmai 50180 Thajsko',
        19.4881446,
        99.4767143,
        '18',
        '6689',
        '71',
        'Denně',
        'Ano',
        '2011',
        'Ron Garl',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Thana City Golf Club',
        'https://www.thaitour.cz/wp-content/uploads/thana-city-004-220x165.jpg',
        'Thana City Golf Club je krásné profesionálně spravované 18 jamkové golfové hřiště, které navrhl designer Greg Norman s použitím hladké trávy, spousty písku a rákosí a vytvořil tak iluzi přímořského hřiště uprostřed největšího rozvoje thajského bydlení. Hřiště bylo...',
        2460,
        '100/2 Moo 4, 14 Bangna – Trad Highway, Bangchalong, Bangplee, Samut Prakarn 10540 Thajsko',
        19.4881446,
        99.4767143,
        '18',
        '6966',
        '72',
        'Denně',
        'Ano',
        '1993',
        'Greg Norman',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Thai Country Club',
        'https://www.thaitour.cz/wp-content/uploads/Thai-20CC-20--20Green-220x165.jpg',
        'Thai Country Club je prestižní a nejlepší mistrovské hřiště v Asii dle časopisu Asian Golf Monthly, nejpopulárnější golfové publikace. Až taková čest byla udělena právě golfovému hřišti Thai Country Club. Opakovaně patří do top 5 golfových hřišt v Asii. Vliv značky...',
        4450,
        '88 Moo 1, Bangna-Trad Km. 35.5, Thambon Pimpa, Bangpakong District, Chacheongsao 24130, Thajsko',
        19.4881446,
        99.4767143,
        '18',
        '7151',
        '72',
        'Denně (mimo pondělí)',
        'Ano',
        '1996',
        'Denis Griffiths',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Suwan Golf & Country Club',
        'https://www.thaitour.cz/wp-content/uploads/Suwan-Golf-220x165.jpg',
        'Suwan Golf & Country Club je novější hřiště na venkově západně od města Bangkok, které leží jen 45 min. cesty od hřiště a kde si golfisté mohou užívat nejlepší povrch a špičkové šikmé a dramatické greeny. Vesnička v okolí dodává hřišti jedinečnost. V okolí jsou...',
        2050,
        '15/3 Moo 2 T. Srisathong, A.Nakornchaisri Nakornpathom, Thajsko',
        19.4881446,
        99.4767143,
        '18',
        '7125',
        '72',
        'Denně',
        'Ano',
        '2005',
        'Weeyos Design',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Riverdale Golf Club',
        'https://www.thaitour.cz/wp-content/uploads/dv7_0755-220x165.jpg',
        'Riverdale Golf Club se nachází nedaleko města Bangkok v okrese Pathumthani. Hřiště bylo poprvé otevřeno 1.8.2010 a navrženo welským architektem Jonathanem Morrow ...',
        3450,
        '123/5 Moo1 Tiwanon Road, Bang Kadi Sub-District, Muang Pathum Thani District ปทุมธานี 12000, Thajsko',
        13.975870,
        100.548940,
        '18',
        '7006',
        '72',
        'Denně',
        'Ne',
        '2010',
        'Jonathan Morrow & Al Tikkanen',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Maung Kaew Golf Club',
        'https://www.thaitour.cz/wp-content/uploads/Muang-20Kaew-200611_H18_3135-220x165.jpg',
        'Mistrovské golfové hřiště s 18 jamkami Muang Kaew Golf Course bylo v roce 2003 předesignováno Lee Schmidtem. Krásné jemné hřiště se zvýšenými greeny nabízí výborné podmínky pro golfovou hru spolu s profesionálními službami. Designer Lee Schmidt umí hřiště navrhnout...',
        2450,
        '52 Moo 8 Bangna-Trad Rd. Km 7.7 Bangkaew Bangplee Samutprakarn, Rachathewa, Bang Phli District, Samut Prakan 10540, Thajsko',
        13.634277,
        100.711281,
        '18',
        '7015',
        '72',
        'Denně',
        'Ano',
        '1992',
        'Lee Schmidt and Brian Curley',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Lam Luk Ka Country Club Thailand',
        'https://www.thaitour.cz/wp-content/uploads/13-West-220x165.jpg',
        'Lam Luk Ka Country Club leží jen kousek od metropole Bangkok a jde o velmi relaxační 36 jamkové golfové hřiště. Nabízí 10.000 stromů, vodní cesty a bujnou přírodu, která je domovem pro více jak 100 druhů volně žijících ptáků a zvířat. K dispozici je hodně stínu...',
        1850,
        '29 Moo 7, Lam Luk Ka Road, Tambon Lamsai, Amphoe Lam Lukka, Patumthani, 12150, Thajsko',
        13.945340,
        100.862910,
        '36',
        '7012/6605',
        '72',
        'Denně',
        'Ano',
        '1994',
        'Roger Packard',
        false,
        true,
        null, 'ADMIN' , null, null);

insert into golf ( name, image, label   , price , location, latitude, longitude, holes, yard, par, opened, driving_range, opening_year, yard_designer, is_favorite, is_active, created_at, created_by, updated_at,updated_by)
values ('Alpine Golf & Sports Club',
        'https://www.thaitour.cz/wp-content/uploads/bg_1-220x165.jpg',
        'Golfové hřiště Alpine Golf & Sports Club bylo navrženo jedním z nejuznávanějších světových architektů, panem Ronaldem M. Garlem a je jedním z nejlepších golfových hřišť v Thajsku se skvělým hodnocením. Leží jen 15 min. od mezinárodního letiště...',
        7400,
        '99 Moo 9, Bangkhan-Sathaneevithayu Road, Klong 5, Klong Luang, Pathumthani 12120, Thajsko',
        14.026110,
        100.662860,
        '18',
        '7044',
        '72',
        'Denně',
        'Ano',
        '1996',
        'Ronald M. Garl',
        false,
        true,
        null, 'ADMIN' , null, null);
