INSERT INTO public.article_tag (article_id, tag_id) VALUES ('0a0b0c3c-0d10-4cc6-8f15-5d49e41b8402', '4cfb637d-1748-4fea-b5cd-a2d7a41dd1e2');
INSERT INTO public.article_tag (article_id, tag_id) VALUES ('0a0b0c3c-0d10-4cc6-8f15-5d49e41b8402', '2249e7ed-ba2b-459a-a4ae-1120421a8404');

INSERT INTO public.article_tag (article_id, tag_id) VALUES ('2b663dcc-9a90-4cc6-a9b2-580bf7893d05', '2249e7ed-ba2b-459a-a4ae-1120421a8404');
INSERT INTO public.article_tag (article_id, tag_id) VALUES ('2b663dcc-9a90-4cc6-a9b2-580bf7893d05', '98e18d76-5a8d-4e78-ac55-d43a524a6469');

INSERT INTO public.article_tag (article_id, tag_id) VALUES ('77aa739a-4dd8-4798-9088-1f2c768f1cba', '98e18d76-5a8d-4e78-ac55-d43a524a6469');
INSERT INTO public.article_tag (article_id, tag_id) VALUES ('77aa739a-4dd8-4798-9088-1f2c768f1cba', '4cfb637d-1748-4fea-b5cd-a2d7a41dd1e2');

INSERT INTO public.article_content (article_id, article_heading, value, priority, created_at, created_by, updated_at, updated_by) VALUES ('0a0b0c3c-0d10-4cc6-8f15-5d49e41b8402', 'Zažijte Porto: Přístav šarmu s vůní vína', 'Přijměte naše pozvání na procházku křivolakými uličkami druhého největšího portugalského města. Porto vás potěší směsí francouzského šarmu, starobylých památek, příjemně inspirativní atmosférou, vůní oceánu i opojnou chutí světoznámého vína. Konec prázdnin a rané babí léto je jako stvořené pro toulky městem, které vyladí vaši duši na frekvenci pohody.',1,'2023-06-28 08:00:44.000000', 'ADMIN', null, null);
INSERT INTO public.article_content (article_id, article_heading, value, priority, created_at, created_by, updated_at, updated_by) VALUES ('0a0b0c3c-0d10-4cc6-8f15-5d49e41b8402', 'Čtvrť Ribeira: klenot s puncem UNESCO', 'O tom, že je Porto městem s jedinečnou osobností a barvitou historií se nejlépe přesvědčíte, navštívíte-li světoznámou čtvrť Ribeira. Svou prohlídku můžete začít na promenádě Cais de Ribeira, která se vine po nábřeží řeky Douro. Během procházky si užijete pohled na dokonale fotogenické vysoké domky s pestrobarevnými fasádami, poklidnou hladinu řeky i radostnou vřavu místních kaváren. Promenáda vás zavede na nevelké náměstí Praca de Ribeira, které zdobí monumentální fontána z roku 1780, celá řada kostelů, středověkých měšťanských domů, palác Casa do Infante, klášter sv. Františka, k jehož výzdobě bylo použito více než 300 kilogramů ryzího zlata, nebo Burzovní palác s dechberoucími interiéry. Obzvláště velkolepým dojmem působí bohatě zdobený Arabský sál.  ',2,'2023-06-28 08:00:44.000000', 'ADMIN', null, null);
INSERT INTO public.article_content (article_id, article_heading, value, priority, created_at, created_by, updated_at, updated_by) VALUES ('0a0b0c3c-0d10-4cc6-8f15-5d49e41b8402', 'Vila Nova de Gaia: místo zaslíbené vínu', 'Levý břeh řeky Douro je zasvěcen vínu. Hlavní turistickou atrakcí jsou desítky vinných sklípků, ve kterých dozrává slavné portské víno. Vychutnejte si sklenku portského, pocházejícího z vinic rozesetých na slunných svazích lemujících řeku Douro. Požitek z degustace ještě umocní procházka po zdejší promenádě s úchvatným výhledem na historické centrum města.',3,'2023-06-28 08:00:44.000000', 'ADMIN', null, null);


INSERT INTO public.article_content (article_id, article_heading, value, priority, created_at, created_by, updated_at, updated_by) VALUES ('2b663dcc-9a90-4cc6-a9b2-580bf7893d05', 'Speciality s vůní orientu aneb Jak chutnají Spojené arabské emiráty' ,'Sedm pohádkově krásných emirátů, které se nachází na východě Arabského poloostrova, láká do své náruče každoročně čím dál více návštěvníků. Moderní mrakodrapy, luxusní hotely, mohutné horské štíty, průzračně čisté moře, písečné duny i špičkové služby, jsou jen zlomkem toho, co můžete v této krásné zemi obdivovat. Bohatý orientální stát si libuje v získávání mnoha světových prvenství. Je libo dotknout se nebe na střeše nejvyšší budovy světa, prohlížet si umělecká díla během potápění, sjíždět na lyžích sjezdovku uprostřed nákupního centra, nebo vypravit do budoucnosti pomocí špičkových technologií? Vítejte ve světě, kde není nic nemožné.',1,'2023-06-28 08:00:44.000000', 'ADMIN', null, null);
INSERT INTO public.article_content (article_id, article_heading, value, priority, created_at, created_by, updated_at, updated_by) VALUES ('2b663dcc-9a90-4cc6-a9b2-580bf7893d05', 'Koření v hlavní roli' ,'Stejně rozmanitá je i zdejší gastronomie. V emirátech žije přes sto různých národností, a právě kulturní mix dává místním specialitám ten pravý šmrnc. Jestli je něco, co opravdu definuje zdejší jídlo, tak je to koření. Vůně kardamonu, kmínu, zázvoru, hřebíčku, drceného pepře, muškátu, šafránu a mnoha dalších se line z restaurací, pouličních bister, i z uliček zdejších tržnic. Ochutnat tu samozřejmě můžete dobroty z celého světa, ale byl by hřích nedat šanci i tradiční arabské kuchyni. A na jaké notoricky známé lahůdky s vůní orientu tu zaručeně natrefíte?',2,'2023-06-28 08:00:44.000000', 'ADMIN', null, null);
INSERT INTO public.article_content (article_id, article_heading, value, priority, created_at, created_by, updated_at, updated_by) VALUES ('2b663dcc-9a90-4cc6-a9b2-580bf7893d05', 'Hummus' ,'Variabilní arabský dip, či pomazánka, kterou miluje celý svět. Rozmixovaná vařená cizrna se ochutí pastou ze sezamu zvanou tahini a přidají se do ní další ingredience. Zpravidla česnek, sůl, olivový olej a citrónová šťáva. Jeho kolébkou je pravděpodobně území dnešního Turecka, ale raketovou rychlostí se dostal i do ostatních koutů zeměkoule. A zvláště v arabských zemích bez něho nedají ani ránu. Existuje v mnoha obměnách a servíruje se tradičně s chlebovou plackou, či syrovou zeleninou. Kromě lahodné chuti se pyšní řadou benefitů, které potěší vaši linii a celkové zdraví. Pokud jste s hummusem ještě neměli tu čest, rozhodně to napravte. Je božský.',3,'2023-06-28 08:00:44.000000', 'ADMIN', null, null);


INSERT INTO public.article_content (article_id, article_heading, value,priority, created_at, created_by, updated_at, updated_by) VALUES ('77aa739a-4dd8-4798-9088-1f2c768f1cba', 'Vydejte se do Makaronésie aneb Ostrovní ráje ve vodách Atlantiku' ,'Kdo by netoužil strávit několik dnů na ostrovech rozesetých ve vodách Atlantiku? Představte si všudypřítomnou sytou zeleň, příjemné subtropické klima, exotické pokrmy i divoké scenérie, které vás nenechají na pochybách, že to, co tyto zdánlivě rozdílné ostrovy spojuje, je jejich sopečný původ. Ať už se rozhodnete pro kterýkoli z nich, věřte, že tu narazíte na místa, která se vám navždy vryjí do paměti, zažijete pocit naprosté volnosti a v nenápadné restauraci na pobřeží vás oslní chuť pokrmů, jejichž tajnou ingrediencí je radost ze života. Přijměte pozvání do Makaronésie, která zahrnuje Kapverdy, Kanárské ostrovy, Madeiru a Azory.',1,'2023-06-28 08:00:44.000000', 'ADMIN', null, null);
INSERT INTO public.article_content (article_id, article_heading, value,priority, created_at, created_by, updated_at, updated_by) VALUES ('77aa739a-4dd8-4798-9088-1f2c768f1cba', 'Kapverdy','Nejjižněji situovanou destinací ze čtyřlístku Makaronéského souostroví jsou turisty stále oblíbenější Kapverdské ostrovy. Svou popularitu získaly nejen kvůli kráse zdejších písčitých pláží, divokým vlnám, jako stvořeným pro surfování, elegantním hotelům i malebným horským vesničkám. Půvaby a rozmanitost zdejších ostrovů okouzlily i slavného britského přírodovědce Charlese Darwina.

Nejnavštěvovanější ostrov Sal se pyšní nejen mezinárodním letištěm, ale také mnoha luxusními hotelovými resorty i libůstkou v podobě solného dolu Pedra Lome. V jeho blízkosti se nachází populární solné jezero, na jehož hladině si užijí vodní radovánky i nezkušení plavci. Ve vlnách Atlantiku si můžete vyzkoušet řadu vodních sportů v čele s kitesurfingem.

Hornatý ostrov Santo Antão láká horaly i vášnivé turisty. Odměnou za mnohdy krkolomné výšlapy jim jsou okouzlující vyhlídky, čerstvý vzduch, osvěžující koupel v horských pramenech i med vonící horskými bylinkami a eukalyptem. Ten je k dostání na trzích v hlavním městě ostrova Riberia Grande. Ostrovní metropole hostí v průběhu srpna a února také proslulé karnevaly.',2,'2023-06-28 08:00:44.000000', 'ADMIN', null, null);
INSERT INTO public.article_content (article_id, article_heading, value,priority, created_at, created_by, updated_at, updated_by) VALUES ('77aa739a-4dd8-4798-9088-1f2c768f1cba', 'Kanárské ostrovy','Tenerife, Gran Canaria, Fuerteventura, Lanzarote, La Palma, La Gomera, El Hierro a Graciosa. Kdo by neznal Kanárské ostrovy – turistické ráje, kde je každé přání předem splněno. Subtropické klima s dlouhými suchými léty a mírnými zimami sem každoročně přiláká na 12 milionů turistů. Jedna z nejmalebnějších částí Atlantiku uspokojí i ty nejnáročnější cestovatele, ale zároveň si stále zachovává svůj přírodní ráz i autentickou atmosféru.

Rušná letoviska, dokonalý plážový servis, drsná krajina, ve které není nouze o skaliska, hluboké kaňony, písečné duny, kaktusy, ale i čarokrásné písčité pláže s pozvolným vstupem do oceánu a tradiční vesničky. Chytáte-li se na dovolenou s dětmi, pak dejte zelenou Gran Canarii.

Chcete-li si užít bezstarostnou plážovou dovolenou, korunovanou výlety do divokého vnitrozemí, kde si zapózujete s instafriendly větrnými mlýny – rezervujte si svůj pobyt na ostrově Fuerteventura.',3,'2023-06-28 08:00:44.000000', 'ADMIN', null, null);


INSERT INTO public.article_images (article_id, value, priority, created_at, created_by, updated_at, updated_by) VALUES ('0a0b0c3c-0d10-4cc6-8f15-5d49e41b8402','https://dcontent.inviacdn.net/shared/img/web-830/2023/8/7/m0/1817763.jpg' ,1,'2023-06-28 08:00:44.000000', 'ADMIN', null, null);
INSERT INTO public.article_images (article_id, value, priority, created_at, created_by, updated_at, updated_by) VALUES ('0a0b0c3c-0d10-4cc6-8f15-5d49e41b8402','https://dcontent.inviacdn.net/shared/img/web-830/2023/8/7/m0/1817971.jpg' ,2,'2023-06-28 08:00:44.000000', 'ADMIN', null, null);
INSERT INTO public.article_images (article_id, value, priority, created_at, created_by, updated_at, updated_by) VALUES ('0a0b0c3c-0d10-4cc6-8f15-5d49e41b8402','https://dcontent.inviacdn.net/shared/img/web-830/2023/8/7/m0/1817975.jpg' ,3,'2023-06-28 08:00:44.000000', 'ADMIN', null, null);

INSERT INTO public.article_images (article_id, value, priority, created_at, created_by, updated_at, updated_by) VALUES ('2b663dcc-9a90-4cc6-a9b2-580bf7893d05','https://dcontent.inviacdn.net/shared/img/web-830/2023/8/9/m0/1821291.jpg' ,1,'2023-06-28 08:00:44.000000', 'ADMIN', null, null);
INSERT INTO public.article_images (article_id, value, priority, created_at, created_by, updated_at, updated_by) VALUES ('2b663dcc-9a90-4cc6-a9b2-580bf7893d05','https://dcontent.inviacdn.net/shared/img/web-830/2023/8/9/m0/1821272.jpg' ,2,'2023-06-28 08:00:44.000000', 'ADMIN', null, null);
INSERT INTO public.article_images (article_id, value, priority, created_at, created_by, updated_at, updated_by) VALUES ('2b663dcc-9a90-4cc6-a9b2-580bf7893d05','https://dcontent.inviacdn.net/shared/img/web-830/2023/8/9/m0/1821273.jpg' ,3,'2023-06-28 08:00:44.000000', 'ADMIN', null, null);


INSERT INTO public.article_images (article_id, value, priority, created_at, created_by, updated_at, updated_by) VALUES ('77aa739a-4dd8-4798-9088-1f2c768f1cba','https://dcontent.inviacdn.net/shared/img/web-830/2023/8/8/m0/1819324.jpg' ,1,'2023-06-28 08:00:44.000000', 'ADMIN', null, null);
INSERT INTO public.article_images (article_id, value, priority, created_at, created_by, updated_at, updated_by) VALUES ('77aa739a-4dd8-4798-9088-1f2c768f1cba','https://dcontent.inviacdn.net/shared/img/web-830/2023/8/8/m0/1819333.jpg' ,2,'2023-06-28 08:00:44.000000', 'ADMIN', null, null);
INSERT INTO public.article_images (article_id, value, priority, created_at, created_by, updated_at, updated_by) VALUES ('77aa739a-4dd8-4798-9088-1f2c768f1cba','https://dcontent.inviacdn.net/shared/img/web-830/2023/8/8/m0/1819334.jpg' ,3,'2023-06-28 08:00:44.000000', 'ADMIN', null, null);
